{{- if .Values.apiserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dt-apiserver
  namespace: {{ .Values.global.nameSpace }}
  labels: 
    app: dt-apiserver
  {{- with .Values.apiserver.serviceAccount.annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{ end }}
{{- end -}}
