{{- if .Values.frontend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dt-frontend
  namespace: {{ .Values.global.nameSpace }}
  labels:
    app: dt-frontend
  {{- with .Values.frontend.serviceAccount.annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{ end }}
{{- end -}}
