apiVersion: v1
kind: Service
metadata:
  name: dt-frontend
  namespace: {{ .Values.global.nameSpace }}
  labels: 
    app: dt-frontend
  {{- with .Values.frontend.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: http
  selector: 
    app: dt-frontend
